### ISSUE TITLE
Possible controller implementation

### ISSUE THREAD

**Issue by lucamarchionna** [eDO-community/eDO_control_v3#2]
Hi everyone, I am working on a project based on visual servoing. This method receives a velocity control input to perform the jog movements. Therefore, I need to change the actual **FollowJointTrajectory** controller into **JointGroupPositionController**. I have implemented this kind of controller in simulation with the _ros_control_ package, but I cannot translate this configuration to the real e.DO. How can I achieve that? 
Thanks in advance, guys.

**Comment by lucamarchionna** [comment]
@ymollard @Bracewind

**Comment by ymollard** [comment]
Hi @lucamarchionna, I believe that you need to write a controller that receives **JointTrajectoryPoint** requests and applies the corresponding jogs to eDO (similarly to the current [JTAS](https://github.com/eDO-community/eDO_control_v3/blob/master/src/joint_trajectory_action_server.py) that receives **JointTrajectory** requests and go through all JointTrjaectoryPoints in it by sending jogs to eDO till the end of the trajectory).

Please use the eDO forum to get help, Github issues are only made for issues.
